dubbo :
  protocol :
    prot : 20880
    name  : dubbo
  application :
    name : service-provider
  registry :
    address : zookeeper://127.0.0.1:2181
  #packageName : com.example.dubbo_provider.services

server :
  port : 8083
